name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - run: cd app/build/outputs/apk; zip -r debug.zip debug; zip -r release.zip release;
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
